development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: neos
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: neos_test
  pool: 5
  username: root
  password: 